### ISSUE TITLE
huggingface 访问不了，如果手动下载模型文件，应该放哪里呢？

### ISSUE THREAD

**Issue by yangyuke001** [studyzy/sd-prompt-translator#5]
huggingface 访问不了，如果手动下载模型文件，应该放哪里呢？

**Comment by xinliqingpi** [comment]
同样问题想问

**Comment by studyzy** [comment]
stable-diffusion-webui/extensions/sd-prompt-translator/scripts/models/models--Helsinki-NLP--opus-mt-zh-en
我本地是这个目录

**Comment by howard-fish** [comment]
为啥我放在stable-diffusion-webui/extensions/sd-prompt-translator/scripts/models/models--Helsinki-NLP--opus-mt-zh-en 这个地方还是不对，提示无法下载
