### ISSUE TITLE
Lora存在被自动翻译的问题

### ISSUE THREAD

**Issue by cklogic** [studyzy/sd-prompt-translator#8]
```
if text_array[i].startswith('<') and text_array[i].endswith('>'):
    continue
```
```
一只鸟在飞,  <lora:可爱国风盲盒:1>
```
![WX20240201-142746@2x](https://github.com/studyzy/sd-prompt-translator/assets/26291070/69889719-ba7d-499e-8b63-4ad1b5ef9c55)

<lora前面是空格的情况会导致满足不了if条件，比如通过点击Lora封面webui自动填入提示词输入框的时候前面会自动填充空格

**Comment by studyzy** [comment]
已修复
